
server:
  port: 8080
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
# make sure endpoints are either secured and/or not reachable from outside
       include: health, caches, env, info, loggers, metrics, mappings

spring:
  application:
    name: Appsfactory Facebook Comments Test
  jmx:
    enabled: false
  jackson:
    default-property-inclusion: non_null
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: MaxB1900
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: 'true'
    hibernate:
      ddl-auto: create-drop

springdoc:
  packagesToScan: appsfactory.facebook.comments.controller.api
  pathsToMatch: /api/**
  swagger-ui:
    path: /swagger-ui/api-docs.html
